[build]
  base = ""
  command = "npm ci --prefix backend && npm ci --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/dist"

[functions]
  directory = "backend/netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
